# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  database_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord
      MYSQL_DATABASE: controlador_pagamentos
    ports:
      - 3309:3306
    expose:
      - 3309
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ControladorPagamento-network
    restart: always

  controladorpagamentofake:
    image: controladorpagamentofake
    build:
      context: .
      dockerfile: src/ControladorPagamento.Fake/Dockerfile
    ports:
      - 5083:5083
    expose:
      - 5083
    environment:
      - TaxaAprovacao=100
      - WebhookUrl=http://ControladorPagamento:5004/Pagamento/webhook
    networks:
      - ControladorPagamento-network
    restart: on-failure

  controladorpagamento:
    image: controladorpagamento
    build:
      context: .
      dockerfile: src/ControladorPagamento/Dockerfile
    ports:
      - 5004:5004
    expose:
      - 5004
    environment:
      - ConnectionStrings__DefaultConnection=server=database_mysql;database=controlador_pagamentos;user=root;password=P@ssWord
      - PagamentoUrl=http://controladorpagamentofake:5083/pagar
    networks:
      - ControladorPagamento-network
    restart: on-failure
    depends_on:
      - database_mysql
      - controladorpagamentofake

networks:
  ControladorPagamento-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
